### ISSUE TITLE
AppData: Custom colors should have higher contrast

### ISSUE THREAD

**Issue by cassidyjames** [ryonakano/pinit#15]
Your custom colors are barely A-level contrast:

https://github.com/ryonakano/pinit/blob/748e0fb642c6904510b37ddbb4fc7b1ea8dfd53e/data/pinit.appdata.xml.in#L80-L81

![Screenshot from 2021-10-06 15-34-28](https://user-images.githubusercontent.com/611168/136286549-aad21c0f-21dd-4b10-892c-9095da2f7823.png)

When used in AppCenter, it's pretty hard to read some parts.

![Screenshot from 2021-10-06 15-35-03](https://user-images.githubusercontent.com/611168/136286610-98cfc44c-f8ea-4246-affb-03d374c7b318.png)

You can use [Harvey](https://appcenter.elementary.io/com.github.danrabbit.harvey.desktop/) to ensure your colors are at least AA level contrast.

**Comment by ryonakano** [comment]
Thank you for your repotting, I fixed this in 9f0b20a. I chose these colors!

![Screenshot from 2021-10-07 07-47-31](https://user-images.githubusercontent.com/26003928/136294163-144dc10c-5dd6-43f7-a08b-ba8c756143f5.png)

Really a nice app :)
