### ISSUE TITLE
The viewport for "edit a desktop file" is broken

### ISSUE THREAD

**Issue by bound-variable** [ryonakano/pinit#25]
The viewport is not resizable and there isn't any scrollbar. The only way to view the entries is to grab the window with a keybinding and move it up off the screen.

![image](https://user-images.githubusercontent.com/51193876/137807848-fc66171f-7bc2-4a54-92c8-d4ce37188d68.png)

- Debian 11
- Gnome 3.38
- Pin It 1.2

**Comment by ryonakano** [comment]
Hi, thank you for using my app in your distribution and reporting the issue! I'll fix it ASAP.

**Comment by Pound-Hash** [comment]
It's already available. That's quick. Thanks again.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
