### ISSUE TITLE
The "edit a desktop file" window is too wide

### ISSUE THREAD

**Issue by Pound-Hash** [ryonakano/pinit#29]
Upon loading, the main window appears fine, as shown in this screenshot:

![image](https://user-images.githubusercontent.com/51193876/142776550-11423b99-248b-4d78-9e3d-7a02807b20f5.png)

The _new file_ option also looks fine. But the _**edit file**_ option opens a window that is too wide:

![image](https://user-images.githubusercontent.com/51193876/142776583-78dd66e1-3355-4041-afd5-50ddc1843226.png)

![image](https://user-images.githubusercontent.com/51193876/142776592-945e8f47-b7c2-423b-a93c-7854a3b0e98b.png)

There's no horizontal scrollbar, so I have to grab the window with the Gnome keybinding (super) and click and drag the whole window to show you the other half.

- Debian 11
- Gnome 3.38.5
- Wayland
- Pinit 1.2.1 (Flatpak)

**Comment by ryonakano** [comment]
I couldn't reproduce the issue but in theory this would happen if the app name or comment are too long. Maybe we should ellipsize them and sho the full text in the tooltip.
