### ISSUE TITLE
Add an app icon

### ISSUE THREAD

**Issue by ryonakano** [ryonakano/pinit#3]
Hi @hanaral, sorry for mentioning you but I'd like to ask you a favor.

You made the app icon for [Louper](https://github.com/ryonakano/louper) before and I really like it. And now I've started developing my fourth app here. Would you mind creating an app icon for this app too?

**Comment by hanaral** [comment]
もちろん！今晩宜しければできますが、多分64、48、24だけですね。

**Comment by ryonakano** [comment]
Hi, thank you very much! How a cute magnet icon! :tada:

I made a branch named [`add-icon`](https://github.com/ryonakano/pinit/tree/add-icons), so now you can fork my repo, switch to that branch, and add your icons. :pray:

I renamed the repo to pinit and replaced any occurrence of "pin-it" in the code to "pinit", so it should be OK now :+1:
