### ISSUE TITLE
The window is not resizable

### ISSUE THREAD

**Issue by machitgarha** [ryonakano/pinit#47]
First of all, thanks for this cool application.

The problem is, I cannot simply resize the window. My screen is small (i.e. 1366x768), so the window is too large to fit there, and I have to move it using Alt + F7 on Gnome to actually see the Save Entry button, for example.

**Comment by machitgarha** [comment]
Cool! Really thanks for the fix!

**Comment by ryonakano** [comment]
Thank you too for using my app and sending a nice feedback! This change will be reflected in the next release of the app.

**Comment by machitgarha** [comment]
Sorry, but the issue is still present with version 1.4.1.

**Comment by ryonakano** [comment]
Hmm strange, I will check it when I back to the keyboard.

**Comment by ryonakano** [comment]
I tested with Pin It! 1.4.1 which is available from Flathub but it resizes as expected:

https://user-images.githubusercontent.com/26003928/167634726-7530fedc-a6e3-4723-a8d8-480f1d22ea72.mp4

But my display size is larger than yours―fortunately I have a laptop with 1366 x 768 display, I'll check the behavior with that laptop.

**Comment by machitgarha** [comment]
I don't meant the general resizing functionality doesn't work, but it doesn't get resized to a lower size. Try resizing it vertically, for example, by lowering its height.

**Comment by ryonakano** [comment]
OK, do you mean the smallest height of the app window is larger than your display height, right?

**Comment by machitgarha** [comment]
Yup, exaclty.
