### ISSUE TITLE
Dark theme style not working

### ISSUE THREAD

**Issue by machitgarha** [ryonakano/pinit#62]
The dark theme style does not work, and after selecting it, the theme remains light. The version I use is 1.4.1.

**Comment by ryonakano** [comment]
Hi, thanks for your reporting. Could you tell me which distribution you're using?

**Comment by machitgarha** [comment]
You're welcome, I should appreciate your work, and I do thank you. :)

I'm on Fedora 35.

**Comment by ryonakano** [comment]
I believe 2.0.0 which is the next version of Pin It! should fix the issue; I confirmed now the app follows and keeps the theme selected by user. The new version will be released soon (maybe at some day during the next week) so keep eyes on that.

If you still face the issue in the new version, please reopen this issue. Thank you very much for using this app and reporting this issue!
