### ISSUE TITLE
Pin It does not display the icons

### ISSUE THREAD

**Issue by Soljanka** [ryonakano/pinit#63]
OS: elementary OS 6.1 Jólnir x86_64
Pin It from flathub: com.github.ryonakano.pinit, version 1.4.1

I have the issue, that the icon in Pin It is not displayed

![Bildschirmfoto von 2022-05-09 13 22 08](https://user-images.githubusercontent.com/7444116/167399921-9c8aff47-c0cf-4154-b5d7-4aeb70bf2c85.png)

The icon is displayed in the menu tho

![Bildschirmfoto von 2022-05-09 13 24 26](https://user-images.githubusercontent.com/7444116/167400413-039e769c-5e7a-47ed-89f6-91ba39a3c85e.png)

journalctl logs the following:
```
com.github.ryon[2662]: Failed to load module "canberra-gtk-module"
com.github.ryon[2662]: FilesView.vala:54: Datei »/home/florian/.var/app/com.valvesoftware.Steam/data/icons/hicolor/256x256/apps/steam_icon_239030.png« konnte nicht geöffnet werden: No such file or directory
com.github.ryon[2662]: FilesView.vala:54: Datei »/home/florian/.wine/drive_c/Program Files (x86)/Sub Culture/ICON/5.png« konnte nicht geöffnet werden: No such file or directory
com.github.ryon[2662]: FilesView.vala:54: Datei »/home/florian/.var/app/com.valvesoftware.Steam/data/icons/hicolor/96x96/apps/steam_icon_212680.png« konnte nicht geöffnet werden: No such file or directory
```
Which is odd - this is definitely the correct path for all three icons.

the canberra-error is also strange; there are a dozen of canberra-libs already installed
```

florian@X302UA178cf8b1:~$ apt list | grep canberra-gtk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libcanberra-gtk-common-dev/focal,focal 0.30-7ubuntu1 all
libcanberra-gtk-dev/focal 0.30-7ubuntu1 amd64
libcanberra-gtk-dev/focal 0.30-7ubuntu1 i386
libcanberra-gtk-module/focal,now 0.30-7ubuntu1 amd64  [installiert]
libcanberra-gtk-module/focal 0.30-7ubuntu1 i386
libcanberra-gtk0/focal,now 0.30-7ubuntu1 amd64  [Installiert,automatisch]
libcanberra-gtk0/focal 0.30-7ubuntu1 i386
libcanberra-gtk3-0/focal,now 0.30-7ubuntu1 amd64  [Installiert,automatisch]
libcanberra-gtk3-0/focal 0.30-7ubuntu1 i386
libcanberra-gtk3-dev/focal 0.30-7ubuntu1 amd64
libcanberra-gtk3-dev/focal 0.30-7ubuntu1 i386
libcanberra-gtk3-module/focal,now 0.30-7ubuntu1 amd64  [Installiert,automatisch]
libcanberra-gtk3-module/focal 0.30-7ubuntu1 i386
```

**Comment by ryonakano** [comment]
Hi, thank you for your reporting and using my apps-Pin It! and Reco 🥳 (which I confirmed from your screenshot).

Just one thing I'd like to confirm is: Did you make your desktop files listed in the first screenshot using Pin It! or using other apps like text editors?
