### ISSUE TITLE
Add the possibility to enter the StartupWMClass

### ISSUE THREAD

**Issue by Soljanka** [ryonakano/pinit#68]
OS: elementary OS 6.1 Jólnir x86_64
Pin It!: com.github.ryonakano.pinit 1.4.1

I really prefer using Pin It! over other applications like menulibre since it fits the minimalistic design of elementary OS. Yet there is one feature that I do miss: a way to add the StartupWMClass to the .deskop file.

Without the StartupWMClass applications will usually run in another instance and not use the entry I pinned to plank:
![Bildschirmfoto von 2022-07-10 12 42 38](https://user-images.githubusercontent.com/7444116/178141628-89349a5d-8c78-4534-a448-894b0e70b064.png)
(Papers, Please does not use the entry I pinned to the dock but another instance without an icon)

This means I usually have to open the .desktop file with a text editor anyway.
![Bildschirmfoto von 2022-07-10 12 56 26](https://user-images.githubusercontent.com/7444116/178141982-e6f2a8f3-965b-4140-b562-2d16f2a3562a.png)
(after addin the StartupWMClass; Papers, Please is not shown as running in another instance)

Proposal: another line in the "Edit Menu" for the Startup WM Class, much like in menulibre
![7oCRkTW](https://user-images.githubusercontent.com/7444116/178141825-ffd2c6e6-2d99-4c0e-8151-2e842f47df27.png)
bonus points for a picker, e.g. click on the magnifying glass and then on the application window to get the correct value

**Comment by ryonakano** [comment]
Hi thank you for your report! I'm happy that you love this app. I'll dig into and work on this in this week.
