### ISSUE TITLE
Pin It! requires a comment, but it is not required by `desktop-file-validate`.

### ISSUE THREAD

**Issue by davidskeck** [ryonakano/pinit#94]
Hello,

When I attempt to create an entry in Pin It! that does not include a comment, the Save button is not enabled. However, if I edit the resulting file to remove the Comment, `desktop-file-validate` sees it as valid and the the .desktop file still works.

**Comment by ryonakano** [comment]
Ah you're right, it's defined as not required in [the specification](https://specifications.freedesktop.org/desktop-entry-spec/1.1/ar01s05.html):

![スクリーンショット 2023-03-18 09 35 20](https://user-images.githubusercontent.com/26003928/226073734-7117d0fd-3fb7-49b5-8171-0e2f0eaf8a2e.png)

It looks like "Categories" also not required, so I'll revisit what is necessary and what is not.
